owner: hamzaremmal
repo: status.remmal.net

sites:
  - name: Personal Website
    url : https://remmal.net
  - name: Status Page
    url: https://status.remmal.net

status-website:
  cname: status.remmal.net
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status | remmal.net
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: 'TODO: FILL THIS'
  navbar:
    - title: Personal Page
      href : https://remmal.net
    - title: Status Page
      href : /
    - title: Site Configuration
      href : https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
